const $=s=>document.querySelector(s), storeKey="mba-radar-v2";
let prefs=JSON.parse(localStorage.getItem(storeKey)||'{"extra":[],"negative":[]}'), active="Current Affairs", stories=[];
const norm=s=>(s||"").toLowerCase(), hits=(text,arr)=>arr.filter(x=>text.includes(norm(x)));
function classify(text, fallback){let best=fallback,n=0;for(const [k,v] of Object.entries(RADAR.clusters)){let h=hits(text,v).length;if(h>n){n=h;best=k}}return best}
function pivot(text){let sets={Strategy:["strategy","market entry","acquisition","merger","m&a","transformation"],Operations:["supply chain","procurement","logistics","manufacturing","inventory","capacity","cost"],Product:["product","launch","innovation","portfolio","approval"],Commercial:["pricing","sales","distribution","market share","marketing","brand","consumer"],Policy:["policy","regulation","rbi","government","budget","tariff"],"Trade & Exports":["export","import","trade","shipping","wto","fta"],Companies:["earnings","quarterly","management commentary","capex"]};let best="Strategy",n=0;for(const[k,v]of Object.entries(sets)){let h=hits(text,v).length;if(h>n){n=h;best=k}}return best}
function score(item,priority,industry){let text=norm(item.title+" "+item.summary), sector=hits(text,RADAR.clusters[industry]||[]), biz=hits(text,RADAR.business), india=/\bindia(n)?\b|rbi|rupee|mumbai|delhi/.test(text), global=/export|import|global|world|china|us |europe|trade|shipping/.test(text), player=(RADAR.players[industry]||[]).find(p=>text.includes(norm(p)));
let junk=hits(text,[...RADAR.negative,...prefs.negative]); if(junk.length && sector.length===0 && biz.length===0)return null;
if(sector.length===0 && biz.length===0 && !player)return null; // adjacency/context gate: generic stories need sector/business context
let rec=10, d=item.date?new Date(item.date):null;if(d&&!isNaN(d)){let days=(Date.now()-d)/864e5;rec=days<=2?10:days<=7?8:days<=14?5:2}
let s=Math.min(100, sector.length*4+Math.min(20,biz.length*4)+(india?15:0)+(player?10:0)+priority*3+rec+(global&&india?5:0)+10);
let why=[sector.slice(0,2).join(", "),biz.slice(0,2).join(", "),india?"India":"",player||"",global?"global/trade":""].filter(Boolean);
return {score:s,reason:"Why ranked: "+(why.join(" · ")||"priority source"),geo:global&&!india?"Global":"India",player}}
function xmlItems(xml,src){let doc=new DOMParser().parseFromString(xml,"text/xml");return [...doc.querySelectorAll("item")].map(i=>{let title=i.querySelector("title")?.textContent?.trim()||"",summary=(i.querySelector("description")?.textContent||"").replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim(),date=i.querySelector("pubDate")?.textContent||"",link=i.querySelector("link")?.textContent?.trim()||"",industry=classify(norm(title+" "+summary),src[1]),rank=score({title,summary,date},+src[3],industry);if(!rank)return null;return{title:title.replace(/\s+-\s+[^–-]+$/,""),summary,date,link,source:src[0],industry,pivot:pivot(norm(title+" "+summary)),...rank}}).filter(Boolean)}
async function fetchSource(src){let proxy="https://api.allorigins.win/raw?url="+encodeURIComponent(src[2]),r=await fetch(proxy);if(!r.ok)throw Error(src[0]);return xmlItems(await r.text(),src)}
function renderTabs(){$("#industryTabs").innerHTML=RADAR.industries.map(x=>`<button class="tab ${x===active?"active":""}" data-tab="${x}">${x}</button>`).join("")}
function visible(){let q=norm($("#search").value),pv=$("#pivotFilter").value,g=$("#geoFilter").value,min=+$("#scoreFilter").value,age=+$("#ageFilter").value;return stories.filter(s=>(active==="Current Affairs"?s.industry==="Current Affairs":s.industry===active)&&(!q||norm(s.title+" "+s.summary+" "+(s.player||"")).includes(q))&&(pv==="all"||s.pivot===pv)&&(g==="all"||s.geo===g)&&s.score>=min&&(!s.date||(Date.now()-new Date(s.date))/864e5<=age))}
function draw(){renderTabs();let v=visible();$("#viewTitle").textContent=active;$("#storyCount").textContent=v.length;$("#sourceCount").textContent=RADAR.sources.length;$("#highCount").textContent=v.filter(x=>x.score>=75).length;let ps=RADAR.players[active]||[];$("#playerCount").textContent=ps.length;$("#players").innerHTML=ps.length?ps.map(p=>`<button class="player" data-player="${p}">${p}</button>`).join(""):"<span class=muted>Select an industry to see tracked players.</span>";$("#sources").innerHTML=RADAR.sources.filter(s=>active==="Current Affairs"?s[1]==="Current Affairs":s[1]===active).map(s=>`<div class=source-row><span>${s[0]}</span><small>P${s[3]}</small></div>`).join("")||"<span class=muted>Cross-sector sources apply.</span>";
let f=$("#feed");f.innerHTML="";if(!v.length)f.innerHTML='<div class="empty">No matching stories yet. Refresh the feeds or loosen a filter.</div>';v.sort((a,b)=>b.score-a.score).forEach(s=>{let n=$("#storyTemplate").content.cloneNode(true);n.querySelector(".source").textContent=s.source;n.querySelector(".score").textContent=`${s.score}/100 ${s.score>=75?"HIGH":s.score>=60?"USEFUL":"DISCOVERY"}`;n.querySelector(".tags").innerHTML=`<span>${s.industry}</span><span>${s.pivot}</span><span>${s.geo}</span>`;let a=n.querySelector(".story-title");a.textContent=s.title;a.href=s.link;n.querySelector(".story-meta").textContent=(s.date?new Date(s.date).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})+" · ":"")+(s.player||"Business signal");n.querySelector(".story-reason").textContent=s.reason;n.querySelector(".original-link").href=s.link;f.append(n)})}
async function refresh(){let b=$("#refreshBtn");b.disabled=true;b.textContent="Collecting…";$("#status").textContent="Reading clustered feeds";let res=await Promise.allSettled(RADAR.sources.map(fetchSource)),m=new Map;res.filter(x=>x.status==="fulfilled").flatMap(x=>x.value).forEach(s=>{let k=norm(s.title).replace(/[^a-z0-9]/g,"");if(!m.has(k)||m.get(k).score<s.score)m.set(k,s)});stories=[...m.values()];localStorage.setItem("mba-radar-stories",JSON.stringify(stories));$("#status").textContent=`${stories.length} ranked · ${res.filter(x=>x.status==="rejected").length} feeds unavailable`;b.disabled=false;b.textContent="Refresh news";draw()}
stories=JSON.parse(localStorage.getItem("mba-radar-stories")||"[]");renderTabs();draw();
$("#industryTabs").onclick=e=>{let b=e.target.closest("[data-tab]");if(b){active=b.dataset.tab;draw()}};
["search","pivotFilter","geoFilter","scoreFilter","ageFilter"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",draw));
$("#players").onclick=e=>{let b=e.target.closest("[data-player]");if(b){$("#search").value=b.dataset.player;draw()}};
$("#refreshBtn").onclick=refresh;$("#settingsBtn").onclick=()=>{$("#extraKeywords").value=prefs.extra.join(", ");$("#extraNegative").value=prefs.negative.join(", ");$("#settingsDialog").showModal()};
$("#saveSettings").onclick=e=>{e.preventDefault();prefs.extra=$("#extraKeywords").value.split(",").map(x=>x.trim()).filter(Boolean);prefs.negative=$("#extraNegative").value.split(",").map(x=>x.trim()).filter(Boolean);localStorage.setItem(storeKey,JSON.stringify(prefs));$("#settingsDialog").close();draw()};